//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4InShip.com.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public int Id { get; set; }
        public string reference_no { get; set; }
        public int Fk_customer_id { get; set; }
        public int Fk_billing_address_id { get; set; }
        public string invoice_number { get; set; }
        public System.DateTime invoice_date { get; set; }
        public bool paid_status { get; set; }
        public System.DateTime paid_on { get; set; }
        public string payment_method { get; set; }
        public decimal payment_amount { get; set; }
        public int transaction_id { get; set; }
        public Nullable<System.Guid> custom_guid { get; set; }
        public string invoice_type { get; set; }
        public short transaction_status { get; set; }
        public string transaction_response { get; set; }
    }
}
