//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4InShip.com.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShipmentDetail
    {
        public int id { get; set; }
        public int Fk_shipment_id { get; set; }
        public string comodity_code { get; set; }
        public string description { get; set; }
        public int quantity { get; set; }
        public decimal purchase_price { get; set; }
    }
}
