//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4InShip.com.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderCharge
    {
        public int id { get; set; }
        public int Fk_order_id { get; set; }
        public string charge_name { get; set; }
        public Nullable<decimal> buy_price { get; set; }
        public Nullable<decimal> sell_price { get; set; }
    }
}
