//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4InShip.com.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddressBook
    {
        public int Id { get; set; }
        public int Fk_customer_Id { get; set; }
        public string address_name { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string company { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string country_code { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string post_code { get; set; }
        public string mobile1 { get; set; }
        public string mobile2 { get; set; }
        public bool is_default { get; set; }
        public string tax_id { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
