//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4InShip.com.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCreditCard
    {
        public int Id { get; set; }
        public int Fk_customer_Id { get; set; }
        public string card_type { get; set; }
        public string card_num { get; set; }
        public string card_expiry { get; set; }
        public string cust_name { get; set; }
        public string cust_address { get; set; }
        public string cust_post_code { get; set; }
        public string cust_country_code { get; set; }
        public string cust_email { get; set; }
        public string cust_mobile { get; set; }
        public string card_auth_id { get; set; }
        public string card_auth_status { get; set; }
        public string card_auth_response { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
