//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4InShip.com.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPackagingOption
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<bool> is_signup { get; set; }
        public Nullable<bool> is_shipment { get; set; }
    }
}
