//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4InShip.com.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlanOptionLinking
    {
        public int Id { get; set; }
        public int Fk_plan_id { get; set; }
        public int Fk_packaging_option_id { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
