//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4InShip.com.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRewardPoint
    {
        public int Id { get; set; }
        public int Fk_CustomerId { get; set; }
        public Nullable<decimal> reward_points { get; set; }
        public Nullable<bool> is_converted { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
    }
}
