//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4InShip.com.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceivedShipment
    {
        public int id { get; set; }
        public int Fk_Customer_Id { get; set; }
        public Nullable<int> Fk_order_id { get; set; }
        public System.DateTime received_date { get; set; }
        public string sender { get; set; }
        public string tracking { get; set; }
        public string carrier { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public string box_condition { get; set; }
        public string staff_comments { get; set; }
        public string user_notes { get; set; }
        public Nullable<bool> is_requested_picture { get; set; }
        public byte status { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string modified_by { get; set; }
        public string created_invoice_file_path { get; set; }
        public string shelf_no { get; set; }
    }
}
